# Generated by Django 2.2.1 on 2019-05-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0002_serie_annee2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carte',
            table=None,
        ),
        migrations.AlterModelTable(
            name='extension',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serie',
            table=None,
        ),
    ]
