# Generated by Django 2.2.1 on 2019-05-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0009_remove_extension_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='type',
        ),
    ]
