# Generated by Django 2.2.1 on 2019-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0012_auto_20190512_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='nameFR',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='carte',
            name='nameUS',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='carte',
            name='nomComplet',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='carte',
            name='nomFrancaisEBAY',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='carte',
            name='num',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='carte',
            name='recherche',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='carte',
            name='sur',
            field=models.TextField(default=0, max_length=120),
        ),
    ]
