# Generated by Django 2.2.1 on 2019-05-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0014_auto_20190512_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='nameFR',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='nameUS',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='nomComplet',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='nomFrancaisEBAY',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='num',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='recherche',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='sur',
        ),
    ]
