# Generated by Django 2.2.1 on 2019-05-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0015_auto_20190512_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension',
            old_name='nom',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='nomDossier',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='nomFR',
            new_name='codeV3',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='nbCartes',
            new_name='isFoilOnly',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='nomRaccourci',
            new_name='keyruneCode',
        ),
        migrations.RenameField(
            model_name='extension',
            old_name='nomUS',
            new_name='mcmName',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='idPCA',
        ),
        migrations.AddField(
            model_name='extension',
            name='isOnlineOnly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extension',
            name='mcmId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extension',
            name='mtgoCode',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='extension',
            name='parentCode',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='extension',
            name='releaseDate',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='extension',
            name='totalSetSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extension',
            name='type',
            field=models.TextField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.TextField(default=0, max_length=120),
        ),
    ]
