# Generated by Django 2.2.1 on 2019-05-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0017_auto_20190513_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='baseSetSize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='block',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='code',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='codeV3',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='isFoilOnly',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='isOnlineOnly',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='keyruneCode',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='mcmName',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='mtgoCode',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='parentCode',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='releaseDate',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='extension',
            name='totalSetSize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='type',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
